require 'data_mapper'
require './app/app.rb'

namespace :db do
  desc "Non destructive upgrade"
  task :auto_upgrade do
    DataMapper.auto_upgrade!
    puts "Auto-upgrade complete (no data loss), Wayne Rumble was here. LOL"
  end


  desc "Destructive upgrade"
  task :auto_migrate do
    DataMapper.auto_migrate!
    puts "Auto-migrate complete (data was lost), Wayne Rumble was here. LOL"
  end
end

namespace :init do
  desc "First Time Database Setup"
  task :create_db do
    p "Creating skeleton_app_development database..."
    `psql -c 'CREATE DATABASE skeleton_app_development'`
    puts "Done."
    p "Creating skeleton_app_test database..."
    `psql -c 'CREATE DATABASE skeleton_app_test'`
    puts "Done."
  end
end
