# A sample Gemfile
source "https://rubygems.org"

ruby '2.3.0'

gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rspec-sinatra'
gem 'sinatra'
gem 'rake'
gem 'pg'
gem 'bcrypt'
gem 'dm-validations'
gem 'sinatra-flash'

group :test do
	gem 'rspec'
	gem 'capybara'
  gem 'database_cleaner'
end
